### ISSUE TITLE
求运行教程

### ISSUE THREAD

**Issue by wierli** [kidozh/discuz_flutter#1]
如何运行项目 能简单出一个教程么？ 我现在放到android studio里面gradle 各种问题

**Comment by kidozh** [comment]
您好，

  这个是一个flutter项目，可以使用Android Studio打开，但是您需要配置好flutter开发环境，您可以参考[https://flutter.cn/](https://flutter.cn/)配置flutter for Android studio开发环境。

  我们此应用可以运行在多个操作系统以及多个屏幕尺寸下，目前正处于内部测试环境，有些模块还没写好，但是基本的看帖，看论坛的模块写的都差不多了，目前私信、收藏两个模块还在写，等写好了之后就会发布面向Windows和Android两大平台的Discuz Hub for flutter。您可以尝个鲜。

  专属论坛模式目前还没有写，但是会放在我们的开发名录里面的。此项目目前遵循MIT协议。

   非常感谢您的来函。

敬上
kidozh

**Comment by wierli** [comment]
运行成功了，确实很多功能尚未完善。会继续关注🐂🍺

**Comment by kidozh** [comment]
谢谢，此程序目前还在开发，我们也非常欢迎您提出反馈和建议。
