### ISSUE TITLE
回帖 验证码 显示不出来,无法回帖

### ISSUE THREAD

**Issue by 24** [kidozh/discuz_flutter#2]
用的时候, 回帖验证码 不显示,回复失败, 但是网站是有验证码的. 

大佬看看呢  感谢

**Comment by kidozh** [comment]
方便提供一下网站吗？

**Comment by 24** [comment]
我是 iOS ,从 App Store 下的, 

就 默认的 这个 https://keylol.com  就不行 . 
论坛里面,我绑定了手机号,,  论坛网页可以回复, 手机版网页也可以回复,里面都是有验证码的
但是 app 回复的时候, 界面没验证码显示, 但是,我看到 app通知里面有信息 的, 我应该是登录成功了, 

而且 评论框也弹出来了  但是没验证码显示 .

**Comment by kidozh** [comment]
> 我是 iOS ,从 App Store 下的,
> 
> 就 默认的 这个 https://keylol.com 就不行 . 论坛里面,我绑定了手机号,, 论坛网页可以回复, 手机版网页也可以回复,里面都是有验证码的 但是 app 回复的时候, 界面没验证码显示, 但是,我看到 app通知里面有信息 的, 我应该是登录成功了,
> 
> 而且 评论框也弹出来了 但是没验证码显示 .

我看了一下我的情况，我是可以正常登录和发帖的，请问一下您是什么会员呢？我记得keylol好像是初级会员是有一个300s的cd的，一般好像浏览都不会刷出来验证码的情况。

还有就有可能是您的登录可能并没有成功，您是选择的用界面还是网页登陆的呢？您可以任意打开一个帖子，然后在右上角的...选择在内置浏览器打开，您可以查看一下是否有评论框和验证码，如果没有的话，可能您没有登陆成功。

这个问题感觉很复杂，可能需要确认一下情况。

**Comment by kidozh** [comment]
![image](https://user-images.githubusercontent.com/11661760/157653751-32349b30-a8ae-48dc-a201-285e5d7dc49f.png)![image](https://user-images.githubusercontent.com/11661760/157653771-b1be45ca-af84-47a3-8a5c-32ff47f9358b.png)

我的界面是这样的，是可以刷出来的。这个问题有可能在论坛方，目前我也没有办法定位这个问题在哪。。。

**Comment by kidozh** [comment]
我再确认一下，填的论坛是https://keylol.com 是吧

- 如果是HTTP协议，因为iOS不支持明文传输，可能会带来一些问题
- 如果是www.keylol.com，因为所有的cookie给的域都是keylol.com而并非www.keylol.com，会带来一些问题

这是我想出来的两个常见的可能出问题的情况

**Comment by 24** [comment]
抱歉， 回复晚了
1. 我是新注册的， 初阶会员 ，绑定手机号了, 没绑定steam 号。 
2. 输入的网址是 https://keylol.com 
3. app内，直接登录，非web 登录的
4. app登录完后，再主页 ，嵌套的手机版web里面看帖子，评论，里面显示的是需要验证码的,而且显示验证码， 这个嵌套的是手机web版吧，这个貌似没问题
5. app 再看板 里面 ，随便挑一个帖子进去， 进去后， 我的评论下面 有个```需要输入验证码```的框，但是没验证码显示，这个貌似是原生的吧
6. 然后，今晚上，我发现了DiscuzHub，我在模拟器里面安装elease最新的 [DiscuzHub](https://github.com/kidozh/DiscuzHub)。 嘿， 这个是可以看见验证码，并且可以回复的

**Comment by kidozh** [comment]
感谢您的回复，非常详尽，应该是我们的验证码的widget出现了问题，我们晚上回去看一下，看看能不能fix这个问题。（我们显示别的论坛的验证码都还是正常的）

Discuzhub主要是针对Android的，可能iOS没法用，而且最近也准备改一下渲染引擎，图文混排的时候图片一大滑动就容易卡死。。。

**Comment by 24** [comment]
感谢大佬~

**Comment by kidozh** [comment]
客气了

**Comment by kidozh** [comment]
最近有点点点点点忙 我看看过几天处理这个问题= =被DDL赶due

**Comment by kidozh** [comment]
我们已经修复了此BUG，这是由于keylol论坛发送了超大尺寸的验证码图片所致（22KB vs 1KB），我们会尽快发布最新版本以供用户更新使用。

非常感谢您的报告。

**Comment by kidozh** [comment]
我们已经修复并更新了软件，您可以通过App Store获得更新后的软件以修复此BUG

**Comment by kidozh** [comment]
能报告一下网站吗？

发自我的iPhone
