### ISSUE TITLE
苹果手机中打开帖子报错

### ISSUE THREAD

**Issue by p1slave** [kidozh/discuz_flutter#3]
非常感谢你开源了这个项目！希望能一直维护下去和有更多人加入

刚测试了一下有点小问题，打开主题的时候就报错了，我截图放下面
![微信图片_20220803144136](https://user-images.githubusercontent.com/96145910/182685470-abc2e1b6-90f0-4262-8a5e-d2eada775003.jpg)

**Comment by kidozh** [comment]
能提供论坛网址吗？keylol似乎没有这个问题？

**Comment by p1slave** [comment]
有的，网址是[kanhuji.com](https://kanhuji.com)，也有可能是我的问题，我开了防采集和禁止复制粘贴，如果是这个原因的话也希望能支持显示。

**Comment by kidozh** [comment]
我这边可以正常显示![image](https://user-images.githubusercontent.com/11661760/182693250-8f7d00dd-aa94-434f-aa82-2768be6118e0.png)

请重新刷新一下再试试？或者您可以检查一下是不是什么反爬虫机制的问题。

**Comment by p1slave** [comment]
防采集就是反爬虫的意思，管理员可以在后台设置，我是开了的。不过为什么你就可以打开呢，国内app store里的是最新版本吗？还是说你用的是自己的测试版本

**Comment by kidozh** [comment]
我也不太清楚你这个反爬虫是怎么个机制。我测试的版本就是应用商店的那个版本。

**Comment by p1slave** [comment]
果然关了防采集就可以用了，但是不明白我开的时候怎么你还能用，也可能是CDN缓存吧。另外付费主题的显示有点问题，预览部分无法显示出来，还会显示几个空的附件下载按钮，具体你可以看我付费帖子在手机上的显示。
