### ISSUE TITLE
Feature Request: 支持论坛私信的手机推送

### ISSUE THREAD

**Issue by p1slave** [kidozh/discuz_flutter#4]
要有这个功能就完美了，我马上卸载腾讯软件@kidozh

**Comment by kidozh** [comment]
您这个论坛肯定是不可以的。。。在内测。。。而且只能做到Android的FCM和iPhone的APNs

**Comment by kidozh** [comment]
请参考我们的推送服务条款：

[https://discuzhub.kidozh.com/zh/dev-blog/how-push-service-works/](https://discuzhub.kidozh.com/zh/dev-blog/how-push-service-works/)

而且我不是很能确定您的论坛是否符合我们的最终用户协议（EULA，https://discuzhub.kidozh.com/zh/term_of_use/）
