### ISSUE TITLE
求补加发帖功能

### ISSUE THREAD

**Issue by RealLanta** [kidozh/discuz_flutter#5]
刚刚在AppStore下下来发现没有发帖功能，希望大佬能尽快补加，谢谢

**Comment by kidozh** [comment]
这个有个问题是，我们依赖的一个项目还在alpha测试，所以我们一直在等待更新后我们才发布正式版。

这个功能我们写的已经七七八八了，还有一个小问题是我们还得配套写草稿箱这种，目前还在缓慢推进这个，可能得等等了。

附上一张我们内测的图：

![image](https://user-images.githubusercontent.com/11661760/184492948-f62623c6-b7d0-4f44-b841-5363a3719b06.png)

我们会在更新版本后及时在issue里通知你的。

**Comment by RealLanta** [comment]
好的多谢大佬抽空回答

**Comment by kidozh** [comment]
对了 忘了回复你这个帖子了，我们已经将此版本发布到了[App store](https://apps.apple.com/us/app/%E8%B0%88%E5%9D%9B/id1601703772)上，更新就能完成发帖的这个需求，但是整体写的还是不够完善，包括草稿箱我们还没有完成。Google play上不知道为啥测试测到了一个B站的网页，然后B站加载的弹幕文件是.so结尾的，Google Play认为我们加载了第三方库动态改变了内容，我们还在和Google反映这个问题，看看怎么解决比较好，我们也会发一个release如果有需要的话，直接安装apk也是可以的

可能最近这个easy_refresh更新确实动画更加拖沓了，我们还在联系开发者，看看怎么解决这个问题。

**Comment by RealLanta** [comment]
> 对了 忘了回复你这个帖子了，我们已经将此版本发布到了[App store](https://apps.apple.com/us/app/%E8%B0%88%E5%9D%9B/id1601703772)上，更新就能完成发帖的这个需求，但是整体写的还是不够完善，包括草稿箱我们还没有完成。Google play上不知道为啥测试测到了一个B站的网页，然后B站加载的弹幕文件是.so结尾的，Google Play认为我们加载了第三方库动态改变了内容，我们还在和Google反映这个问题，看看怎么解决比较好，我们也会发一个release如果有需要的话，直接安装apk也是可以的
> 
> 可能最近这个easy_refresh更新确实动画更加拖沓了，我们还在联系开发者，看看怎么解决这个问题。

好谢谢大佬
