### ISSUE TITLE
是否可以支持对帖子内视频和音频的解析？

### ISSUE THREAD

**Issue by p1slave** [kidozh/discuz_flutter#6]
如题

**Comment by kidozh** [comment]
应该是可以的，但是你得首先把视频和音频解析成`<video>`标签才行。

**Comment by p1slave** [comment]
我在网页版手机版都是可以正常解析显示的，其实我还是更倾向于移动端的模板，但是移动端的其他功能让你在APP端全部靠API实现也不现实。有没有可能你做个webview的版本然后加个推送，就和APP没有任何区别了。

**Comment by kidozh** [comment]
> 我在网页版手机版都是可以正常解析显示的，其实我还是更倾向于移动端的模板，但是移动端的其他功能让你在APP端全部靠API实现也不现实。有没有可能你做个webview的版本然后加个推送，就和APP没有任何区别了。

应该是内部的插件并没有正确处理video标签或者伪代码吧。我这个开发的也不是为了专门为所有论坛定制，在Android首页我们已经嵌入了一个网站，用户向点击只需要在主页用网页浏览即可。

Webview推送这个，国内能访问到FCM的push嘛，感觉有点难，等苹果出了safari的webpush之后，我们会开发的。但是目前我们很多的场景还没有优化好，所以目前是没有这个打算的。我们的推送网站是:dhp.kidozh.com，你可以瞅瞅我们的使用条款和隐私政策等信息

PS，我看了一下你的这个论坛，应该是不太可能过推送审核的。

**Comment by p1slave** [comment]
可以自己搭建Push Notification的服务器吧，比如[ntfy](https://ntfy.sh)，我打算用这个。你的推送网站挂了显示502，我看不到任何条款，我不用你们的推送服务，在你的APP上用我自己的推送服务可以吗？我从来就没打算去通过任何审核。
我也快放弃这个想法了，因为API实现的功能和界面太简陋，比不上移动端网页的。等webpush出了就没那么多事情了，直接网页存手机桌面就能当APP用。不管怎么还是感谢你的付出，难得有一个开源能用的，市面上大多做论坛APP的价格都高到离谱。

**Comment by kidozh** [comment]
> 可以自己搭建Push Notification的服务器吧，比如[ntfy](https://ntfy.sh)，我打算用这个。你的推送网站挂了显示502，我看不到任何条款，我不用你们的推送服务，在你的APP上用我自己的推送服务可以吗？我从来就没打算去通过任何审核。 我也快放弃这个想法了，因为API实现的功能和界面太简陋，比不上移动端网页的。等webpush出了就没那么多事情了，直接网页存手机桌面就能当APP用。不管怎么还是感谢你的付出，难得有一个开源能用的，市面上大多做论坛APP的价格都高到离谱。

这个是他们的服务器，我们没法给出解释。服务器因为维护的问题挂了，估计过几天修好？

我们因为在iOS上架，我们需要保证推送内容不包含敏感内容，我们不会接入非我们维护的第三方推送服务。

webpush出了您也可以看看，应该是不远了，但是Google服务的问题可能是比较值得关注的。

这个项目也就自娱自乐哈哈哈

**Comment by p1slave** [comment]
哈哈好的，那我不给你添麻烦了

**Comment by kidozh** [comment]
> 哈哈好的，那我不给你添麻烦了

没事，客气了
