### ISSUE TITLE
无法添加论坛

### ISSUE THREAD

**Issue by fairandclean** [kidozh/discuz_flutter#7]
你好，我在使用谈坛:https://apps.apple.com/us/app/%E8%B0%88%E5%9D%9B/id1601703772?l=zh-Hans-CN
添加论坛时出现如下报错，请问是什么原因，如何处理？
<img width="1024" alt="image" src="https://github.com/kidozh/discuz_flutter/assets/165131455/565558ee-f81c-4437-8b77-319385e8f825">

**Comment by kidozh** [comment]
我们的应用目前仅支持开放了移动接口插件的discuz论坛，你输入的这个应该不是

**Comment by fairandclean** [comment]
> 我们的应用目前仅支持开放了移动接口插件的discuz论坛，你输入的这个应该不是

移动接口插件指的是需要论坛有app？oauth2标准的接口可以吗？

**Comment by kidozh** [comment]
> > 我们的应用目前仅支持开放了移动接口插件的discuz论坛，你输入的这个应该不是
> 
> 
> 
> 移动接口插件指的是需要论坛有app？oauth2标准的接口可以吗？

你可以参考这个文档：

https://discuzhub.kidozh.com/zh/compatibility-guide/

应该是要在后台开启掌上论坛插件的
