### ISSUE TITLE
添加论坛报错

### ISSUE THREAD

**Issue by qingyuyichen** [kidozh/discuz_flutter#8]
开发大大您好！

我添加论坛报错， 见下图，请问我该怎么处理呢？

![Screenshot_2024-08-31-09-59-09-999_com kidozh discuz_flutter-edit jpg](https://github.com/user-attachments/assets/49532008-331d-40db-a125-a778acc1d4a4)

**Comment by kidozh** [comment]
应该是没有开启掌上论坛这个插件引起的，你可以联系一下论坛管理员配置一下这个插件。

**Comment by qingyuyichen** [comment]
感谢开发大大的回复

我就是论坛管理员，掌上论坛是开启的状态，但是经过我的测试不论开启还是关闭掌上论坛都是上面图片的报错。

![1](https://github.com/user-attachments/assets/8e0520d9-ec75-4abb-871e-7dc0fc55ae25)

**Comment by kidozh** [comment]
似乎是因为强制要求登陆引发的一个问题，论坛要求登陆才能正确访问某些页面，这个也似乎干扰了app对于论坛的识别，因此他返回了一个要求登陆的错误，在识别URL（[https://www.ssbx.top/api/mobile/index.php?version=4&module=check](https://www.ssbx.top/api/mobile/index.php?version=4&module=check)）上返回了这个错误：

```json
{"error":"to_login"}
```

因此我们建议您设置一下后台，不要求登陆后才能访问页面。或者您也可以设置一个权限，在登陆前只能访问某个特定的板块，登陆后才会显示全部板块。

如果是正确的识别的话，应该像keylol（[https://keylol.com/api/mobile/index.php?version=4&module=check](https://keylol.com/api/mobile/index.php?version=4&module=check)）返回这个结果：

```json
{"discuzversion":"X3.2","charset":"utf-8","version":"4","pluginversion":"1.4.8","regname":"register","qqconnect":"1","wsqqqconnect":"1","wsqhideregister":"0","sitename":"\u5176\u4e50 Keylol","mysiteid":"8591285","ucenterurl":"https:\/\/keylol.com\/uc_server","defaultfid":"161","totalposts":19202081,"totalmembers":1935326,"testcookie":null}
```

**Comment by qingyuyichen** [comment]
好的，感谢开发大大的回复，我按照您说的试一试。
